import MagicString from 'magic-string';
import { parse } from '@babel/parser';
import _traverse from '@babel/traverse';

// Handle CJS/ESM interop
const traverse = _traverse.default || _traverse;

/**
 * Inline get(), cell(), put(), set(), and bind() calls
 *
 * The key optimization is wholesale inlining of bind() callback bodies at set() locations.
 * Instead of using effect loops, we:
 * 1. Find all bind(cell, callback) calls
 * 2. Store refs to DOM elements: cell.ref_N = element
 * 3. At set() locations, inline the callback body with element vars replaced by cell.ref_N
 *
 * Transforms:
 *   get(cell) -> cell.v
 *   cell(value) -> { v: value, e: [] }
 *   put(cell, value) -> cell.v = value
 *   set(cell, value) -> { cell.v = value; <inlined callback bodies> }
 *   bind(cell, callback) -> cell.ref_N = element; (callback inlined at set() locations)
 */

/**
 * Check if a node is a get() call
 */
function isGetCall(node) {
	return (
		node?.type === 'CallExpression' &&
		node.callee?.type === 'Identifier' &&
		node.callee.name === 'get'
	);
}

/**
 * Check if a node is a cell() call
 */
function isCellCall(node) {
	return (
		node?.type === 'CallExpression' &&
		node.callee?.type === 'Identifier' &&
		node.callee.name === 'cell'
	);
}

/**
 * Check if a node is a put() call
 */
function isPutCall(node) {
	return (
		node?.type === 'CallExpression' &&
		node.callee?.type === 'Identifier' &&
		node.callee.name === 'put'
	);
}

/**
 * Check if a node is a set() call
 */
function isSetCall(node) {
	return (
		node?.type === 'CallExpression' &&
		node.callee?.type === 'Identifier' &&
		node.callee.name === 'set'
	);
}

/**
 * Check if a node is a bind() call
 */
function isBindCall(node) {
	return (
		node?.type === 'CallExpression' &&
		node.callee?.type === 'Identifier' &&
		node.callee.name === 'bind'
	);
}

/**
 * Find ref assignments at the component level (NOT inside bind() callbacks).
 * These are generated by codegen for simple bindings without bind():
 *   element.property = expression;  (where expression contains get(cell))
 *   cell.ref_N = element;
 *
 * Returns a map: cellCode -> [{ refNum, property, updateExpr }]
 */
function findRefAssignmentsWithoutBind(ast, code) {
	// Map: cellCode -> [{ refNum, property, updateExpr }]
	const refMappings = new Map();

	// Helper to process statements from a callback body
	function processStatements(statements) {
		// Build a map: elementVar -> { property, updateExpr, cellCodes }
		// from element.property = expression assignments
		const elementAssignments = new Map();

		// First pass: find element.property = expression (with get(cell) calls)
		for (const stmt of statements) {
			if (
				stmt.type === 'ExpressionStatement' &&
				stmt.expression.type === 'AssignmentExpression' &&
				stmt.expression.operator === '=' &&
				stmt.expression.left.type === 'MemberExpression' &&
				stmt.expression.left.object.type === 'Identifier' &&
				stmt.expression.left.property.type === 'Identifier'
			) {
				const elementVar = stmt.expression.left.object.name;
				const property = stmt.expression.left.property.name;
				const rightExpr = stmt.expression.right;

				// Check if the expression contains get() calls
				const cellCodes = findGetCallCells(rightExpr, code);
				if (cellCodes.length > 0) {
					// Get the full expression and transform get(x) to x.v
					let updateExpr = code.slice(rightExpr.start, rightExpr.end);
					updateExpr = updateExpr.replace(/\bget\(([^)]+)\)/g, '$1.v');

					elementAssignments.set(elementVar, {
						property,
						updateExpr,
						cellCodes,
					});
				}
			}
		}

		// Second pass: find cell.ref_N = element assignments
		// Handle both simple identifiers (count.ref_1) and member expressions (row.label.ref_1)
		for (const stmt of statements) {
			if (
				stmt.type === 'ExpressionStatement' &&
				stmt.expression.type === 'AssignmentExpression' &&
				stmt.expression.operator === '=' &&
				stmt.expression.right.type === 'Identifier'
			) {
				const left = stmt.expression.left;
				let cellCode = null;
				let refProp = null;

				// Pattern 1: cell.ref_N (simple identifier)
				if (
					left.type === 'MemberExpression' &&
					left.object.type === 'Identifier' &&
					left.property.type === 'Identifier' &&
					left.property.name.startsWith('ref_')
				) {
					cellCode = left.object.name;
					refProp = left.property.name;
				}
				// Pattern 2: obj.cell.ref_N (member expression like row.label.ref_1)
				else if (
					left.type === 'MemberExpression' &&
					left.object.type === 'MemberExpression' &&
					left.property.type === 'Identifier' &&
					left.property.name.startsWith('ref_')
				) {
					cellCode = code.slice(left.object.start, left.object.end);
					refProp = left.property.name;
				}

				if (cellCode && refProp) {
					const refNum = parseInt(refProp.replace('ref_', ''), 10);
					const elementVar = stmt.expression.right.name;

					// Look up the element assignment
					const elemInfo = elementAssignments.get(elementVar);
					if (elemInfo && elemInfo.cellCodes.includes(cellCode)) {
						if (!refMappings.has(cellCode)) {
							refMappings.set(cellCode, []);
						}
						refMappings.get(cellCode).push({
							refNum,
							property: elemInfo.property,
							updateExpr: elemInfo.updateExpr,
						});
					}
				}
			}
		}
	}

	traverse(ast, {
		CallExpression(path) {
			const node = path.node;

			// Find this.connected() calls
			if (
				node.callee?.type === 'MemberExpression' &&
				node.callee.object?.type === 'ThisExpression' &&
				node.callee.property?.type === 'Identifier' &&
				node.callee.property.name === 'connected' &&
				node.arguments.length >= 1
			) {
				const callbackArg = node.arguments[0];
				if (
					callbackArg.type !== 'ArrowFunctionExpression' &&
					callbackArg.type !== 'FunctionExpression'
				) {
					return;
				}

				const body = callbackArg.body;
				const statements = body.type === 'BlockStatement' ? body.body : [body];
				processStatements(statements);
			}

			// Find for_block() calls and process their render callbacks
			if (
				node.callee?.type === 'Identifier' &&
				node.callee.name === 'for_block' &&
				node.arguments.length >= 3
			) {
				const callbackArg = node.arguments[2];
				if (
					callbackArg.type !== 'ArrowFunctionExpression' &&
					callbackArg.type !== 'FunctionExpression'
				) {
					return;
				}

				const body = callbackArg.body;
				const statements = body.type === 'BlockStatement' ? body.body : [body];
				processStatements(statements);
			}
		},
		noScope: true,
	});

	return refMappings;
}

/**
 * Extract the property pattern from a cell code
 * e.g., "row.is_selected" -> { pattern: "is_selected", prefix: "row" }
 * e.g., "count" -> null (simple identifier, no pattern)
 */
function extractPropertyPattern(cellCode) {
	const match = cellCode.match(/^([a-zA-Z_][a-zA-Z0-9_]*)\.([a-zA-Z_][a-zA-Z0-9_]*)$/);
	if (match) {
		return { prefix: match[1], pattern: match[2] };
	}
	return null;
}

/**
 * Find all cell codes referenced by get() calls in an expression
 */
function findGetCallCells(node, code) {
	const cellCodes = [];

	function visit(n) {
		if (!n) return;
		if (isGetCall(n) && n.arguments[0]) {
			cellCodes.push(code.slice(n.arguments[0].start, n.arguments[0].end));
			return;
		}
		for (const key of Object.keys(n)) {
			const child = n[key];
			if (child && typeof child === 'object') {
				if (Array.isArray(child)) {
					child.forEach(visit);
				} else if (child.type) {
					visit(child);
				}
			}
		}
	}

	visit(node);
	return cellCodes;
}

/**
 * Find all for_block variable assignments and map cell names to for_block variable names
 * Looks for patterns like: rows_for_block = for_block(container, rows, ...)
 */
function findForBlockMappings(ast, code) {
	const mappings = new Map();

	traverse(ast, {
		AssignmentExpression(path) {
			const node = path.node;
			if (
				node.left.type === 'Identifier' &&
				node.left.name.endsWith('_for_block') &&
				node.right.type === 'CallExpression' &&
				node.right.callee?.type === 'Identifier' &&
				node.right.callee.name === 'for_block' &&
				node.right.arguments.length >= 2
			) {
				const forBlockVarName = node.left.name;
				const cellArg = node.right.arguments[1];
				const cellCode = code.slice(cellArg.start, cellArg.end);
				mappings.set(cellCode, forBlockVarName);
			}
		},
		noScope: true,
	});

	return mappings;
}

/**
 * Find all bind() calls and extract callback info for inlining
 * Returns a map from cell code -> array of callback info
 */
function findBindCallbacks(ast, code) {
	// Map: cellCode -> [{ callbackBody, elementVars, refNum, paramName, statementStart, statementEnd }]
	const bindCallbacks = new Map();
	// Track ref numbers per cell
	const refCounters = new Map();

	traverse(ast, {
		ExpressionStatement(path) {
			const expr = path.node.expression;
			if (!isBindCall(expr)) return;

			const cellArg = expr.arguments[0];
			const callbackArg = expr.arguments[1];
			if (!cellArg || !callbackArg) return;

			// Get callback info
			if (
				callbackArg.type !== 'ArrowFunctionExpression' &&
				callbackArg.type !== 'FunctionExpression'
			) {
				return;
			}

			const cellCode = code.slice(cellArg.start, cellArg.end);
			const paramName = callbackArg.params[0]?.name || 'v';

			// Get the callback body
			const body = callbackArg.body;
			let bodyCode;
			if (body.type === 'BlockStatement') {
				// Extract statements from block, removing braces
				bodyCode = code.slice(body.start + 1, body.end - 1).trim();
			} else {
				// Expression body
				bodyCode = code.slice(body.start, body.end);
			}

			// Find element variables used in the callback (e.g., p_1_text, tr_1)
			const elementVars = findElementVariables(body, code);

			// Get or create ref number for this cell
			const currentRef = refCounters.get(cellCode) || 0;
			const refNum = currentRef + 1;
			refCounters.set(cellCode, refNum);

			// Store bind callback info
			if (!bindCallbacks.has(cellCode)) {
				bindCallbacks.set(cellCode, []);
			}

			bindCallbacks.get(cellCode).push({
				callbackBody: bodyCode,
				elementVars,
				refNum,
				paramName,
				statementStart: path.node.start,
				statementEnd: path.node.end,
			});
		},
		noScope: true,
	});

	return bindCallbacks;
}

/**
 * Find element variables used in a callback body
 * Looks for element.property = ... patterns
 */
function findElementVariables(body, code) {
	const elementVars = [];
	const seen = new Set();

	function visit(node) {
		if (!node) return;

		// Look for element.property = ... patterns
		if (
			node.type === 'AssignmentExpression' &&
			node.left.type === 'MemberExpression' &&
			node.left.object.type === 'Identifier'
		) {
			const varName = node.left.object.name;
			if (!seen.has(varName)) {
				seen.add(varName);
				elementVars.push({ varName });
			}
		}

		// Recurse into child nodes
		for (const key of Object.keys(node)) {
			const child = node[key];
			if (child && typeof child === 'object') {
				if (Array.isArray(child)) {
					child.forEach(visit);
				} else if (child.type) {
					visit(child);
				}
			}
		}
	}

	visit(body);
	return elementVars;
}

/**
 * Transform a callback body for inlining at a set() location
 * - Replace element variables with cell.ref_N
 * - Replace callback parameter (v) with cell.v
 * - Transform get() calls to .v access
 */
function transformCallbackBody(bodyCode, cellCode, elementVars, paramName, refNum) {
	let transformed = bodyCode;

	// Replace the callback parameter (v) with cell.v
	const paramRegex = new RegExp(`\\b${paramName}\\b`, 'g');
	transformed = transformed.replace(paramRegex, `${cellCode}.v`);

	// Replace element variables with cell.ref_N
	for (const { varName } of elementVars) {
		const varRegex = new RegExp(`\\b${varName}\\b`, 'g');
		transformed = transformed.replace(varRegex, `${cellCode}.ref_${refNum}`);
	}

	// Transform any remaining get() calls to .v access
	transformed = transformed.replace(/\bget\(([^)]+)\)/g, '$1.v');

	return transformed;
}

/**
 * Generate ref assignment code: cell.ref_N = elementVar
 */
function generateRefAssignment(cellCode, elementVar, refNum) {
	return `${cellCode}.ref_${refNum} = ${elementVar};`;
}

/**
 * Transform all get(), cell(), put(), set(), and bind() calls
 */
export function inlineGetCalls(code, filename) {
	const ast = parse(code, {
		sourceType: 'module',
		plugins: ['jsx'],
	});

	const s = new MagicString(code);

	// Find for_block mappings (cell name -> for_block variable name)
	const forBlockMappings = findForBlockMappings(ast, code);

	// Find all bind() callbacks for inlining
	const bindCallbacks = findBindCallbacks(ast, code);

	// Find ref assignments without bind() (from codegen's direct ref approach)
	const refWithoutBind = findRefAssignmentsWithoutBind(ast, code);

	// Track all calls to transform
	const getCalls = [];
	const cellCalls = [];
	const putCalls = [];
	const setCalls = [];

	// Track bind statements to remove
	const bindStatementsToRemove = [];

	// Track rift-js imports for removal
	const importsToRemove = [];

	// Collect bind statements to remove
	for (const [cellCode, callbacks] of bindCallbacks) {
		for (const cb of callbacks) {
			bindStatementsToRemove.push({
				start: cb.statementStart,
				end: cb.statementEnd,
				cellCode,
				callback: cb,
			});
		}
	}

	traverse(ast, {
		CallExpression(path) {
			if (isGetCall(path.node)) {
				const arg = path.node.arguments[0];
				if (arg) {
					getCalls.push({
						start: path.node.start,
						end: path.node.end,
						argCode: code.slice(arg.start, arg.end),
					});
				}
			} else if (isCellCall(path.node)) {
				const arg = path.node.arguments[0];
				cellCalls.push({
					start: path.node.start,
					end: path.node.end,
					argStart: arg?.start,
					argEnd: arg?.end,
				});
			} else if (isPutCall(path.node)) {
				const cellArg = path.node.arguments[0];
				const valueArg = path.node.arguments[1];
				if (cellArg) {
					putCalls.push({
						start: path.node.start,
						end: path.node.end,
						cellStart: cellArg.start,
						cellEnd: cellArg.end,
						valueStart: valueArg?.start,
						valueEnd: valueArg?.end,
					});
				}
			} else if (isSetCall(path.node)) {
				const cellArg = path.node.arguments[0];
				const valueArg = path.node.arguments[1];
				if (cellArg) {
					const cellCode = code.slice(cellArg.start, cellArg.end);
					setCalls.push({
						start: path.node.start,
						end: path.node.end,
						cellStart: cellArg.start,
						cellEnd: cellArg.end,
						cellCode,
						valueStart: valueArg?.start,
						valueEnd: valueArg?.end,
						forBlockVar: forBlockMappings.get(cellCode) || null,
					});
				}
			}
		},
		ImportDeclaration(path) {
			const source = path.node.source.value;
			if (source === 'rift-js') {
				for (const specifier of path.node.specifiers) {
					if (specifier.type === 'ImportSpecifier') {
						const name = specifier.imported.name;
						if (['get', 'cell', 'put', 'set', 'bind'].includes(name)) {
							importsToRemove.push({ name, specifier });
						}
					}
				}
			}
		},
		noScope: true,
	});

	// Sort all calls by position descending (process from end to start)
	const allCalls = [
		...getCalls.map((c) => ({ ...c, type: 'get' })),
		...cellCalls.map((c) => ({ ...c, type: 'cell' })),
		...putCalls.map((c) => ({ ...c, type: 'put' })),
		...setCalls.map((c) => ({ ...c, type: 'set' })),
	].sort((a, b) => b.start - a.start);

	// Process calls
	for (const call of allCalls) {
		if (call.type === 'get') {
			s.overwrite(call.start, call.end, `${call.argCode}.v`);
		} else if (call.type === 'cell') {
			const argCode = call.argStart != null ? s.slice(call.argStart, call.argEnd) : 'undefined';
			s.overwrite(call.start, call.end, `{ v: ${argCode}, e: [] }`);
		} else if (call.type === 'put') {
			const cellCode = s.slice(call.cellStart, call.cellEnd);
			const valueCode =
				call.valueStart != null ? s.slice(call.valueStart, call.valueEnd) : 'undefined';
			s.overwrite(call.start, call.end, `(${cellCode}.v = ${valueCode})`);
		} else if (call.type === 'set') {
			const c = s.slice(call.cellStart, call.cellEnd);
			const v = call.valueStart != null ? s.slice(call.valueStart, call.valueEnd) : 'undefined';

			if (call.forBlockVar) {
				// Cell has an associated for_block - use .update()
				s.overwrite(call.start, call.end, `{ ${c}.v = ${v}; ${call.forBlockVar}.update(); }`);
			} else {
				// Check if this cell has bind callbacks to inline (exact match first)
				let callbacks = bindCallbacks.get(call.cellCode);
				let callbackCellCode = call.cellCode;

				// If no exact match, try pattern match (e.g., "prev.is_selected" matches "row.is_selected")
				if ((!callbacks || callbacks.length === 0) && call.cellCode.includes('.')) {
					const patternInfo = extractPropertyPattern(call.cellCode);
					if (patternInfo) {
						// Look for any bind callback with matching property pattern
						for (const [existingCellCode, existingCallbacks] of bindCallbacks) {
							const existingPattern = extractPropertyPattern(existingCellCode);
							if (existingPattern && existingPattern.pattern === patternInfo.pattern) {
								callbacks = existingCallbacks;
								callbackCellCode = existingCellCode;
								break;
							}
						}
					}
				}

				if (callbacks && callbacks.length > 0) {
					// Inline the bind callback bodies wholesale
					const inlinedUpdates = callbacks
						.map((cb) => {
							// Transform callback body, substituting the actual cell code's prefix
							let body = transformCallbackBody(
								cb.callbackBody,
								callbackCellCode,
								cb.elementVars,
								cb.paramName,
								cb.refNum
							);
							// If we pattern-matched, replace the original prefix with the actual one
							if (callbackCellCode !== call.cellCode) {
								const originalPattern = extractPropertyPattern(callbackCellCode);
								const actualPattern = extractPropertyPattern(call.cellCode);
								if (originalPattern && actualPattern) {
									// Replace "row.is_selected.ref_N" with "prev.is_selected.ref_N"
									const regex = new RegExp(
										`\\b${originalPattern.prefix}\\.${originalPattern.pattern}\\b`,
										'g'
									);
									body = body.replace(regex, `${actualPattern.prefix}.${actualPattern.pattern}`);
								}
							}
							return body;
						})
						.join(' ');

					s.overwrite(call.start, call.end, `{ ${c}.v = ${v}; ${inlinedUpdates} }`);
				} else {
					// Check for ref assignments without bind() (exact match first)
					let refInfos = refWithoutBind.get(call.cellCode);
					let refCellCode = call.cellCode;

					// If no exact match, try pattern match
					if ((!refInfos || refInfos.length === 0) && call.cellCode.includes('.')) {
						const patternInfo = extractPropertyPattern(call.cellCode);
						if (patternInfo) {
							for (const [existingCellCode, existingRefInfos] of refWithoutBind) {
								const existingPattern = extractPropertyPattern(existingCellCode);
								if (existingPattern && existingPattern.pattern === patternInfo.pattern) {
									refInfos = existingRefInfos;
									refCellCode = existingCellCode;
									break;
								}
							}
						}
					}

					if (refInfos && refInfos.length > 0) {
						// Generate direct DOM updates using the refs
						const directUpdates = refInfos
							.map((info) => {
								let update = `${refCellCode}.ref_${info.refNum}.${info.property} = ${info.updateExpr};`;
								// If pattern-matched, replace the original prefix with actual
								if (refCellCode !== call.cellCode) {
									const originalPattern = extractPropertyPattern(refCellCode);
									const actualPattern = extractPropertyPattern(call.cellCode);
									if (originalPattern && actualPattern) {
										const regex = new RegExp(
											`\\b${originalPattern.prefix}\\.${originalPattern.pattern}\\b`,
											'g'
										);
										update = update.replace(
											regex,
											`${actualPattern.prefix}.${actualPattern.pattern}`
										);
									}
								}
								return update;
							})
							.join(' ');

						s.overwrite(call.start, call.end, `{ ${c}.v = ${v}; ${directUpdates} }`);
					} else {
						// No bind callbacks or refs - use the generic effect loop
						s.overwrite(
							call.start,
							call.end,
							`{ ${c}.v = ${v}; for (let i = 0; i < ${c}.e.length; i++) ${c}.e[i](${c}.v); }`
						);
					}
				}
			}
		}
	}

	// Remove bind statements and add ref assignments in their place
	// Sort by position descending
	bindStatementsToRemove.sort((a, b) => b.start - a.start);

	for (const { start, end, cellCode, callback } of bindStatementsToRemove) {
		// Generate ref assignment for each element variable
		let refAssignment = '';
		for (const { varName } of callback.elementVars) {
			refAssignment += generateRefAssignment(cellCode, varName, callback.refNum);
		}

		// Replace bind() call with ref assignment(s)
		if (refAssignment) {
			s.overwrite(start, end, refAssignment);
		} else {
			// No element vars found - just remove the bind statement
			// Remove the whole line including newline
			let removeEnd = end;
			if (code[removeEnd] === '\n') removeEnd++;
			s.remove(start, removeEnd);
		}
	}

	// Remove imports that are no longer needed
	// Collect all imports to remove first
	const shouldRemoveBind = bindStatementsToRemove.length > 0;
	const importsToActuallyRemove = importsToRemove.filter(({ name }) => {
		return (
			(name === 'get' && getCalls.length > 0) ||
			(name === 'cell' && cellCalls.length > 0) ||
			(name === 'put' && putCalls.length > 0) ||
			(name === 'set' && setCalls.length > 0) ||
			(name === 'bind' && shouldRemoveBind)
		);
	});

	// Sort by position
	importsToActuallyRemove.sort((a, b) => a.specifier.start - b.specifier.start);

	// Remove from right to left to preserve positions
	for (let i = importsToActuallyRemove.length - 1; i >= 0; i--) {
		const { specifier } = importsToActuallyRemove[i];
		const isLast = i === importsToActuallyRemove.length - 1;
		const isFirst = i === 0;

		// Check if this is the first import (after opening brace)
		const beforeSpecifier = code.slice(Math.max(0, specifier.start - 2), specifier.start);
		const afterSpecifier = code.slice(specifier.end, specifier.end + 2);

		let startPos = specifier.start;
		let endPos = specifier.end;

		if (afterSpecifier.startsWith(', ')) {
			// Remove trailing ", "
			endPos = specifier.end + 2;
		} else if (afterSpecifier.startsWith(',')) {
			// Remove trailing ","
			endPos = specifier.end + 1;
		} else if (beforeSpecifier.endsWith(', ')) {
			// No trailing comma - remove leading ", "
			startPos = specifier.start - 2;
		}

		s.remove(startPos, endPos);
	}

	return {
		code: s.toString(),
		map: s.generateMap({
			source: filename,
			file: filename + '.map',
			includeContent: true,
		}),
	};
}
